In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [0]:
swap = arr1
swap[:,[0,3]]=swap[:,[3,0]]

In [0]:
swap

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [0]:
arr1[::-1,:]

array([[18, 16, 17, 15, 19],
       [13, 11, 12, 10, 14],
       [ 8,  6,  7,  5,  9],
       [ 3,  1,  2,  0,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [0]:
mean = np.nanmean(arr2)
mask = np.isnan(arr2)
arr2[mask]=mean
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [2]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[28, 63, 50, 46],
       [72,  7, 56, 70],
       [29,  1, 67, 16],
       [46, 40, 96,  3],
       [27, 20, 95, 49]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [15]:
mask2 = ((arr3>25) | (arr3%3==0))
print(arr3[mask2])

[28 63 50 46 72 56 70 29 67 46 40 96  3 27 95 49]


In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:
print(f'10th percentile of arr3 : {(np.percentile(arr3,10))}')
print(f'25th percentile of arr3 : {(np.percentile(arr3,25))}')
print(f'50th percentile of arr3 : {(np.percentile(arr3,50))}')

10th percentile of arr3 : 3.9000000000000004
25th percentile of arr3 : 28.75
50th percentile of arr3 : 43.0
